### ISSUE TITLE
I can't set DIImageView in another view.

### ISSUE THREAD

**Issue by pratik1311** [danielinoa/DIImageView#9] opened 2017-07-20 12:04 UTC
Hi @danielinoa 

I want to add DIImageView in to other view that is IBOutlet in storyboard. When I set that image is not displaying.

        let imageView = DIImageView(image: postImage)
        imageView.contentMode = .scaleAspectFill
        self.imageContainerView = imageView

If I add in view then its working file

        let imageView = DIImageView(image: postImage)
        imageView.contentMode = .scaleAspectFill
        view = imageView

Please help me I want to add image view in another view.

Thanks,
Pratik

**Comment by pratik1311** [comment] 2017-07-21 12:24
@danielinoa  
Please help me. I need it and its urgent.

**Comment by danielinoa** [comment] 2017-07-21 19:27
Sure. I'll help you.
Can you provide a sample project with what you are trying to achieve?

**Comment by pratik1311** [comment] 2017-07-22 05:10
Hi Daniel,

Thanks for reply.

https://www.dropbox.com/s/l99ibdbme3j65c7/DIImageViewDemo.zip?dl=0

I have added code in above link. Please check and let me know.

Thanks.
Pratik

**Comment by danielinoa** [comment] 2017-07-22 06:16
Pratik,

The issue is the following:
We have `self.imageContainerView = imageView` in line `22` of `ViewController.swift`. This has your **`weak`** property `imageContainerView` point to thew newly created `imageView`. This will result in `imageContainerView` being `nil` at the end of `viewDidLoad`.

Additionally, even if `imageContainerView` was a strong property, it would not retain any layout information from the view (instantiated through Interface Builder) it pointed to before pointing to `imageView`. Since you cannot point to a new view and retain attributes from the previous instance.

The simplest solution to your issue would be to:

- Make `imageContainerView`, in `Main.storyboard`, is a `UImageView`.
- Set both its class and module to `DIImageView` in the Identity Inspector.
- Assign the image in the Attribute Inspector.
- Set `imageContainerView` as a `DIImageView` IBOutlet on `ViewController`

I believe this should fix your issue.

-------

Aside from your issue, there is a known layout bug in `DIImageView` that is noticeable when the imageView is not as wide as the screen. I plan to fix this shortly.

**Comment by danielinoa** [comment] 2017-07-22 06:56
The aforementioned bug has been fixed in `1.0.3`.

**Comment by pratik1311** [comment] 2017-07-22 09:33
Hi Daniel,
I set imageContainerView, in Main.storyboard, is a UImageView. Image is coming but its touch is not working. I can't add caption now.

Please send me code back with solution.

**Comment by danielinoa** [comment] 2017-07-22 09:48
[DIImageViewDemo.zip](https://github.com/danielinoa/DIImageView/files/1167257/DIImageViewDemo.zip)

**Comment by pratik1311** [comment] 2017-07-22 10:55
HI Daniel,
Its working fine.

Thanks for you help.

**Comment by danielinoa** [comment] 2017-07-22 10:56
You're welcome.

**Closed as completed by danielinoa** 2017-07-22 10:56 UTC
